# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='sym',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
